### ISSUE TITLE
Versions past 1.1 not compatible with android 4.4

### ISSUE THREAD

**Issue by jakepu2** [lukeaschenbrenner/TxtNet-Browser#12]
Versions 2.0 and beyond of the browser apk get a parsing error when it is attempted to install on a phone running android 4.4.2. I am unsure if this is intended or not because I could not find a more detailed changelog of the 2.0 release other than the one provided in the releases tab, and the version comparisons on github look like hyroglyphics to me.
-Edit: I just used a tool for getting apk info and it seems like the most recent release is compatible with android 5 while versions 1 and 1.1 are compatible with android kitkat. I would still like to know if this is an intended/necessary change and for what feature if thats ok.

**Comment by lukeaschenbrenner** [comment]
Thanks for reporting. This is not an intended change at all - I didn't have an Android 4.4 device or emulator to test on, and there must have been a breaking change made between the two versions. I will look into this and get back to you shortly.

**Comment by lukeaschenbrenner** [comment]
@jakepu2 , can you please check now to verify that the app works? In addition, if you can, please test the server too (you will need a PC to run the ADB commands on Android 4.4). If you can't test, no worries.

**Comment by jakepu2** [comment]
Unfortunately I can't help test much, as my android 4 phone is just a spare without a number. But i was able to install the apk on it without the parsing error I would get on previous versions. Sorry I couldn't be of more help, this is a really cool project with less attention than it deserves.

**Comment by lukeaschenbrenner** [comment]
That's fine, I appreciate your testing on an actual KitKat device regardless. Thanks for the kind words, I'd love to see more people find this project useful too!
