### ISSUE TITLE
Not working (sweden (+46))

### ISSUE THREAD

**Issue by J-Emil-P** [lukeaschenbrenner/TxtNet-Browser#19]
Time tested: 21:29-12:44 (GMT+2)
Phone: samsung galaxy a41 | android 12 | not rooted
I cannot seem to use the service, I just get loading.
Carrier: fello
Carrier based on: telia
I used the number +19132032719
I send messages to the number but I have not gotten a response, 5 messages sent.
Yes I gave it all the permissions and default sms app

**Comment by Emil-P-kod** [comment]
I have tried a bunch more and it sends all of the same message except a few which just contain `Website Cancel`

**Comment by lukeaschenbrenner** [comment]
It was possible that the server was down (I'm in the process of debugging issues with Android doze killing the server.) Can you try again now?

**Comment by Emil-P-kod** [comment]
I'll try now

**Comment by Emil-P-kod** [comment]
Does not seem to work

**Comment by lukeaschenbrenner** [comment]
Thanks for the reply. I'll manually check the message log to see if the server was able to receive anything from you and report back. In the meantime, can you try sending the message "£, ¥, è, Γ, Λ, Ω, Π, Ψ, Σ, Θ, Ξ, ΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦΦ" to another phone and determine if the message was 1. received with all characters fully intact and 2. check that the message is not broken up into chunks according to your SMS app before it is sent (should say something like 0/160).

**Comment by Emil-P-kod** [comment]
It was received via sms and there was a 0 when sending. 

Here is an example of one the messages i sent to the server (the latest one):

00@(:ÆS4¤Äè¤)då;s!>wt5kÖ,¥vm_jk/dy(sPy@öwß?ìwÄöZvUDL¡:àààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààà

**Comment by lukeaschenbrenner** [comment]
I just verified that I have received your messages (I assume the original message was sent on 6/27) and that the server had replied to all of your messages. It's possible that either your carrier is blocking inbound SMS, or you setting TxtNet Browser as your default SMS app is causing problems. This is a known issue #4 , so please try without it as the default SMS app and report back.

**Comment by Emil-P-kod** [comment]
It was received via sms and there was a 0 when sending. 

Here is an example of one the messages i sent to the server (the latest one):

00@(:ÆS4¤Äè¤)då;s!>wt5kÖ,¥vm_jk/dy(sPy@öwß?ìwÄöZvUDL¡:àààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààà

**Comment by Emil-P-kod** [comment]
I have tried with default and without. Messages says I have not received anything. And yes that is the correct date for the first message.

**Comment by Emil-P-kod** [comment]
Here is the details of my phone contract (translated by google lens) https://pasteboard.co/nQooWSj7Qkcn.png  (github upload did not work) i will check some settings tomorrow since it is now 1:57 for me.

**Comment by lukeaschenbrenner** [comment]
It's difficult to tell from that translation, but it appears that it is only explicitly mentioned that outbound SMS to non EU-countries is free. Perhaps inbound SMS from non-EU countries is not free? I would get in contact with your carrier to confirm this. From my end, I know that my carrier only supports SMS to the following Swedish carriers: 

GOTANET	
HI3G ACCESS AB
LYCAMOBILE- SWE
MUNDIO MOBILE LIMITED
TDC MOBIL- SWE
TELE 2 AB
TELENOR SVERIGE AB
TELIASONERA MOBILE NETWORKS AB SWEDEN

**Comment by Emil-P-kod** [comment]
In swedish it does not say either if inbound works. 
Fello (my carrier) works with the telia network.

**Comment by Emil-P-kod** [comment]
Maybe fello is blocking it
Other sweeds have the same problem with 2fa 
https://swedroid.se/forum/threads/fello-traden-om-fello-telias-naet.117923/page-76 

Translated https://swedroid-se.translate.goog/forum/threads/fello-traden-om-fello-telias-naet.117923/page-76?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=sv&_x_tr_pto=wapp

**Comment by ElliotS2007** [comment]
I seem to have the same problem. I'm on a Danish carrier (Telmore, using TDC) and it don't seem to get any messages either.

**Comment by lukeaschenbrenner** [comment]
@ElliotS2007 Your issue is likely unrelated; the server went down on Thu/Fri of last week and I have yet to contact my server's carrier to fix. Sorry for the inconvenience and I hope you get a chance to test it out soon!

**Comment by ElliotS2007** [comment]
Maybe, maybe not, it has never worked on my devices. It could just be that I’m unlucky and have hit the server when it was offline. I tried it from the 18. to 21. may and June 3. And it hasn’t worked a single time.

**Comment by ElliotS2007** [comment]
Maybe, maybe not, it has never worked on my devices. It could just be that I’m unlucky and have hit the server when it was offline. I tried it from the 18. to 21. may and June 3. And it hasn’t worked a single time.

**Comment by lukeaschenbrenner** [comment]
Once I get the time to sort things out with the carrier, I'll reply to this thread so that you can test during a timeframe when I can guarantee uptime. Given what you've said about multiple attempts though, perhaps something similar is happening to you as with Emil-P-kod.
