### ISSUE TITLE
[Question] Paid SMS sending

### ISSUE THREAD

**Issue by Pheggas** [lukeaschenbrenner/TxtNet-Browser#21]
Hello. Many carriers have sending SMS paid (0,04€ / SMS for example). How many SMSs are sent when trying to load some site. I understand it can depend on what site i'm about to load but grab `wikipedia.org` as an example. I saw some people have sent over 30 SMS to load one website. That means 1,20€ with an example tariff.

Is this correct or only one SMS is sent to receive whole website?

**Comment by lukeaschenbrenner** [comment]
I need to run some updated tests to provide more recent/accurate estimates of SMS traffic, but for a text-heavy website like a Wikipedia article, you should absolutely expect around or over 30 SMS messages for just the one website. Consider the amount of SMS it would take to just send the article text alone, which is much more than one SMS. The level of compression that Brotli achieves is impressive, but it is not able to reduce the size of the output by anything like 90%. Sorry that SMS is so expensive in your country, unfortunately, it seems like this project might not be a good solution for you. If you have any ideas of want to provide insight into other possible less expensive ways of transmitting information in your country feel free to reply! I'd appreciate your thoughts.

**Comment by lukeaschenbrenner** [comment]
No problem, I'm glad that you found it useful!

**Comment by lukeaschenbrenner** [comment]
Hi @Pheggas , I hope you don't mind me reaching out after quite a long time. I got the opportunity to work with some people who are doing a professional user study on TxtNet to figure out what direction would be most impactful for the future of the project. They're looking to ask a few questions to people who have interest in the app for specific uses. I was looking back and saw that you were interested in TxtNet as an emergency internet backup. I would love if you would be willing to chat with us and answer a few questions. If you're able please send an email to my inbox (email address in my profile). Thanks!
