### ISSUE TITLE
Issue with hosting server

### ISSUE THREAD

**Issue by NoSadBeHappy** [lukeaschenbrenner/TxtNet-Browser#23]
![Screenshot_20230704-132848.png](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/95050434/015c7453-cd00-44ba-b810-c3af538fc7d4)

![Screenshot_20230704-132826.png](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/95050434/dad36406-350a-4b46-b545-283152c62391)

As you can see, all permissions are allowed, but I still can't run the server as it gives me an error. What am I missing? Thanks for the help.

**Comment by lukeaschenbrenner** [comment]
What Android version? Did you install Shizuku and enable TxtNet permissions? Have you enabled "Draw over other apps" permission (in app info settings screen, doesn't show up in permissions screen)?

**Comment by lukeaschenbrenner** [comment]
Since I haven't gotten a reply from this issue in a while, I'm closing it for inactivity.
