### ISSUE TITLE
How do I start the browser?

### ISSUE THREAD

**Issue by felixhume** [lukeaschenbrenner/TxtNet-Browser#24]
![Screenshot_20230722_150617_TxtNet Browser](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/50804992/f2bca141-6b0c-49f6-86ef-a548f4cfbc09)
There is no option to start browsing or anything, I'm just stuck on this page.

**Comment by lukeaschenbrenner** [comment]
Sorry for the confusing user flow - UI design is not my forte! Simply hit the back button on your phone on perform the back gesture and you will be taken back to the main browser screen.

**Comment by felixhume** [comment]
Thanks
