### ISSUE TITLE
Philippines Server when?? (+63)

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [lukeaschenbrenner/TxtNet-Browser#27]
i dont know how to code but when will a philippine server release??? Or could you provide me how to set up server

**Comment by lukeaschenbrenner** [comment]
Feel free to check the documentation to learn how to set up your own server. At the bare minimum, you only need a dedicated Android smartphone and SMS plan to host your own server! Reply if you have any issues setting one up.
