### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by TIGERSUSYT** [lukeaschenbrenner/TxtNet-Browser#33]
I install the app, allow all the permissions, but I'm stuck on this screen
![Screenshot_20240608_131535_com txtnet txtnetbrowser](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/130369040/78f4ddf5-d723-4001-846e-6e17f048905b)
What do i do?
Info about my phone:
Model - honor 20 yal-l21
Sim with unlimited sms to any number
Latvian number
Currently in Finland

**Comment by ErikUden** [comment]
Same problem, sadly

**Comment by lukeaschenbrenner** [comment]
Hello, sorry for the long delay in responses. The UI isn't clear, but at this screen you're intended to populate the (empty) list with at least one server phone number. You can do this by pressing the + (plus) in the top right corner, typing in a server instance number (example in readme), and hitting save. Then, tap on the number now in the list to select it, and perform a back gesture. I will try to make this more clear in upcoming releases!
