### ISSUE TITLE
Why doesn't it allow me to type in a server number? 

### ISSUE THREAD

**Issue by Jeffyzf079** [lukeaschenbrenner/TxtNet-Browser#38]
The app installs but the it takes me to a black screen and tells me to input a server number via a message that appears at the bottom of my screen but then there's not a single place I'm able to enter a number.

**Comment by lukeaschenbrenner** [comment]
Hi, sorry for the confusing initial UI, but there's actually a "+" button on the top right hand corner of the screen. I'm currently in contact working on a possibility of UI improvements in the app in the near future.
