### ISSUE TITLE
New phone number

### ISSUE THREAD

**Issue by weissnichtmehr** [lukeaschenbrenner/TxtNet-Browser#5]
Hi, could you add more international phone numbers? I live in Germany for example, and i have to pay 0.87€ per SMS to Amerika 🥲

**Comment by lukeaschenbrenner** [comment]
I totally understand. I'm in the middle of completely overhauling the server backend to be entirely functional on an unrooted Android phone without the usage of an external API. This will make it easy for anyone to setup their own server number. The only requirements are a local phone plan, an (extra) Android phone, and an internet connection. In testing, I will be renting a few international numbers for others to test so international SMS fees can be avoided. I can't guarantee I will be able to get ahold of a German number that has cheap international roaming for sent messages (I'm located in the US), but keep an eye out for updates!
